# Generated by Django 2.2 on 2021-09-29 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sy', '0001_initial'),
        ('crm', '0001_initial'),
        ('gl', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inv', '0001_initial'),
        ('ap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyers',
            name='buyergroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.BuyersGroups', verbose_name='Buyer Group'),
        ),
        migrations.AddField(
            model_name='buyers',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.Buyers', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='buyers',
            name='reportingto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Buyers_ReportingTo', to='ap.Buyers', verbose_name='Reporting To'),
        ),
        migrations.AddField(
            model_name='buyers',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='vendorcostbalances',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsCostBalances_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='vendorcostbalances',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsCostBalances_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='vendorcostbalances',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsCostBalances_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='vendorcostbalances',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsCostBalances_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='vendorcostbalances',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.Vendors', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='accountsize',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'AccountSize'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_accountsize', to='sy.LookUp', verbose_name='Account Size'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='agingstyle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.AgingStyles', verbose_name='Aging Style'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='apledger',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': 'True'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='AP. Ledger'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='businessactivitytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.BusinessActivitiesTypes', verbose_name='Business Activity Type'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Vendors_Buyer', to='ap.Buyers', verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Languages', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.Vendors', verbose_name='Parent vendor'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='paymenttearm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.PaymentsTearms', verbose_name='Payments Tearms'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='status',
            field=models.ForeignKey(limit_choices_to={'keyname': 'AccountStatus'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_status', to='sy.LookUp', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='statuschangedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='vendorcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.VendorsCategories', verbose_name='vendor Category'),
        ),
        migrations.AddField(
            model_name='vendors',
            name='vendorclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.VendorsClasses', verbose_name='vendor Class'),
        ),
        migrations.AddField(
            model_name='vendorsaddresses',
            name='addresstype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.AddressesTypes', verbose_name='Address Type'),
        ),
        migrations.AddField(
            model_name='vendorsaddresses',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Cities', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='vendorsaddresses',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Countries', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='vendorsaddresses',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Districts', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='vendorsaddresses',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.Vendors', verbose_name='vendor'),
        ),
        migrations.AddField(
            model_name='vendorscategories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.VendorsCategories', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='vendorsclasses',
            name='agingstyle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.AgingStyles', verbose_name='Aging Style'),
        ),
        migrations.AddField(
            model_name='vendorsclasses',
            name='apledger',
            field=models.ForeignKey(limit_choices_to={'allowaccountentry': 'True'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='AP. Ledger'),
        ),
        migrations.AddField(
            model_name='vendorsclasses',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='vendorsclasses',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='vendorsclasses',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Languages', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='vendorsclasses',
            name='paymenttearm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.PaymentsTearms', verbose_name='Payments Tearms'),
        ),
        migrations.AddField(
            model_name='vendorscontacts',
            name='contacttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.ContactsTypes', verbose_name='Contact Type'),
        ),
        migrations.AddField(
            model_name='vendorscontacts',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.Vendors', verbose_name='vendor'),
        ),
        migrations.AddField(
            model_name='vendorsjour',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsJour_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='vendorsjour',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currenct'),
        ),
        migrations.AddField(
            model_name='vendorsjour',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsJour_operation', to='inv.Operations', verbose_name='Operation'),
        ),
        migrations.AddField(
            model_name='vendorsjour',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'RecordStatus'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsJour_Status', to='sy.LookUp', verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='vendorsjour',
            name='statuschangedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By'),
        ),
        migrations.AddField(
            model_name='vendorsjour',
            name='transtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TransTypes', verbose_name='Trans Type'),
        ),
        migrations.AddField(
            model_name='vendorsjourline',
            name='accounttype',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('keyid', 90001), ('keyid', 90002), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsJourLine_AccountType', to='sy.LookUp', verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='vendorsjourline',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsJourLine_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='vendorsjourline',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsJourLine_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='vendorsjourline',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsJourLine_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='vendorsjourline',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsJourLine_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='vendorsjourline',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currenct'),
        ),
        migrations.AddField(
            model_name='vendorsjourline',
            name='ledger',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='Ledger'),
        ),
        migrations.AddField(
            model_name='vendorsjourline',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.Vendors', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='vendorsjourline',
            name='vendorjour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.VendorsJour', verbose_name='Vendor Jour'),
        ),
        migrations.AddField(
            model_name='vendorspayments',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPayments_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='vendorspayments',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPayments_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='vendorspayments',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPayments_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='vendorspayments',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPayments_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='vendorspayments',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VendorsPayments_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='vendorspayments',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPayments_Currency', to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='vendorspayments',
            name='paymentdirection',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'PaymentDirection'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPayments_PaymentDirection', to='sy.LookUp', verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='vendorspayments',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPayments_Paymethod', to='sy.PaymentsMethods', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='vendorspayments',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'PaymentStatus'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPayments_Status', to='sy.LookUp', verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='vendorspayments',
            name='transtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TransTypes', verbose_name='Trans Type'),
        ),
        migrations.AddField(
            model_name='vendorspayments',
            name='treasuryorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TreasuriesOrders', verbose_name='Treasury Order'),
        ),
        migrations.AddField(
            model_name='vendorspayments',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.Vendors', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='vendorspaymentsline',
            name='accounttype',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'AccountType'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPaymentsLine_accounttype', to='sy.LookUp', verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='vendorspaymentsline',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPaymentsLine_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='vendorspaymentsline',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPaymentsLine_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='vendorspaymentsline',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPaymentsLine_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='vendorspaymentsline',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPaymentsLine_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='vendorspaymentsline',
            name='ledger',
            field=models.ForeignKey(limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsPaymentsLine_account', to='gl.Ledger', verbose_name='Ledger'),
        ),
        migrations.AddField(
            model_name='vendorspaymentsline',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.Vendors', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='vendorspaymentsline',
            name='vendorpayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.VendorsPayments', verbose_name='Vendor Payment'),
        ),
        migrations.AddField(
            model_name='vendorstrans',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsTrans_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='vendorstrans',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsTrans_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='vendorstrans',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsTrans_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='vendorstrans',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsTrans_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='vendorstrans',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VendorsTrans_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='vendorstrans',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='vendorstrans',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.VendorsPayments', verbose_name='Vendors Payment Key'),
        ),
        migrations.AddField(
            model_name='vendorstrans',
            name='postby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VendorsTrans_PostBy', to=settings.AUTH_USER_MODEL, verbose_name='Post By'),
        ),
        migrations.AddField(
            model_name='vendorstrans',
            name='transtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TransTypes', verbose_name='Trans Type'),
        ),
        migrations.AddField(
            model_name='vendorstrans',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsTrans_vendor', to='ap.Vendors', verbose_name='Vendor'),
        ),
        migrations.AddField(
            model_name='vendorstrans',
            name='vendorjour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='VendorsTrans_LedgerJour', to='ap.VendorsJour', verbose_name='Vendors Jour'),
        ),
        migrations.AlterField(
            model_name='vendorsclasses',
            name='allowchaneged',
            field=models.BooleanField(blank=True, default=False, verbose_name='Allow Change Class info'),
        ),
        migrations.AlterField(
            model_name='vendorsjour',
            name='islocked',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Locked'),
        ),
    ]
