# Generated by Django 2.2.3 on 2022-03-25 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0004_auto_20220317_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationstypes',
            name='accounttype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OperationsTypes_accounttype', to='ap.Vendors', verbose_name='Account Type'),
        ),
    ]
