# Generated by Django 2.2.3 on 2022-03-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0006_auto_20220325_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationstypes',
            name='accounttype',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'AccountType'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OperationsTypes_accounttype', to='sy.LookUp', verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='operationkind',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'OperationsKinds'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='OperationsTypes_operationkind', to='sy.LookUp', verbose_name='Operation Kind'),
        ),
    ]
