# Generated by Django 2.2.3 on 2022-04-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0007_auto_20220328_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationsline',
            name='remainquantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True, verbose_name='RemainQuantity'),
        ),
    ]
