# Generated by Django 2.2.3 on 2022-04-28 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0008_operationsline_remainquantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoriesbinlocations',
            name='barcode',
            field=models.CharField(max_length=100, unique=True, verbose_name='Barcode'),
        ),
    ]
