# Generated by Django 2.2.3 on 2022-05-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0009_auto_20220428_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoriesbinlocations',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Barode'),
        ),
        migrations.AlterField(
            model_name='inventoriesbinlocations',
            name='code',
            field=models.CharField(blank=True, max_length=100, unique=True, verbose_name='Auto Code Concat(L+I+F+Z+T+S+B)'),
        ),
    ]
