# Generated by Django 2.2.3 on 2022-05-31 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sy', '0006_auto_20220330_1512'),
        ('inv', '0010_auto_20220523_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencies',
            name='taxgrouppurchases',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Items_taxgroupheadPurchases', to='sy.TaxesGroups', verbose_name='Tax Group Head Purchases'),
        ),
        migrations.AddField(
            model_name='agencies',
            name='taxgrouppurchasesincludedprice',
            field=models.BooleanField(default=False, verbose_name='Tax Included Purchase Price'),
        ),
        migrations.AddField(
            model_name='agencies',
            name='taxgroupsales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Items_taxgroupheadsales', to='sy.TaxesGroups', verbose_name='Tax Group Head Sales'),
        ),
        migrations.AddField(
            model_name='agencies',
            name='taxgroupsalesincludedprice',
            field=models.BooleanField(default=False, verbose_name='Tax Included sale Price'),
        ),
    ]
