# Generated by Django 2.2 on 2022-01-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gl', '0002_auto_20210929_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgerjour',
            name='created_by',
        ),
    ]
