# Generated by Django 2.2 on 2022-01-20 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gl', '0004_remove_treasuriesorders_approvalby'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasuriesorders',
            name='approvalby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TreasuriesOrders_approvalby', to=settings.AUTH_USER_MODEL, verbose_name='Approval By'),
        ),
    ]
