# Generated by Django 2.2 on 2021-09-29 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210929_1512'),
        ('ar', '0002_auto_20210929_1512'),
        ('inv', '0002_auto_20210929_1512'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gl', '0002_auto_20210929_1512'),
        ('bnk', '0002_auto_20210929_1512'),
        ('sy', '0002_auto_20210929_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='cashdiscount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_cashdiscount', to='sy.CashDiscountsRoles', verbose_name='Cash Discount'),
        ),
        migrations.AddField(
            model_name='customers',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='customers',
            name='customercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.CustomersCategories', verbose_name='Customer Category'),
        ),
        migrations.AddField(
            model_name='customers',
            name='customerclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.CustomersClasses', verbose_name='Customer Channel'),
        ),
        migrations.AddField(
            model_name='customers',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Languages', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='customers',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Customers', verbose_name='Parent Customer'),
        ),
        migrations.AddField(
            model_name='customers',
            name='paymenttearm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.PaymentsTearms', verbose_name='Payments Tearms'),
        ),
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.ForeignKey(limit_choices_to={'keyname': 'AccountStatus'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_status', to='sy.LookUp', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='customers',
            name='statuschangedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By'),
        ),
        migrations.AddField(
            model_name='customers',
            name='visitclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.VisitsClasses', verbose_name='Visit Class'),
        ),
        migrations.AddField(
            model_name='customersaddresses',
            name='addresstype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.AddressesTypes', verbose_name='Address Type'),
        ),
        migrations.AddField(
            model_name='customersaddresses',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Cities', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='customersaddresses',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Countries', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='customersaddresses',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Customers', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='customersaddresses',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Districts', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='customerscategories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.CustomersCategories', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='customersclasses',
            name='agingstyle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.AgingStyles', verbose_name='Aging Style'),
        ),
        migrations.AddField(
            model_name='customersclasses',
            name='arledger',
            field=models.ForeignKey(limit_choices_to={'allowaccountentry': 'True'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='AR. Ledger'),
        ),
        migrations.AddField(
            model_name='customersclasses',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='customersclasses',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Languages', verbose_name='Language'),
        ),
        migrations.AddField(
            model_name='customersclasses',
            name='paymenttearm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.PaymentsTearms', verbose_name='Payments Tearms'),
        ),
        migrations.AddField(
            model_name='customersclasses',
            name='pricelevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.PriceLevels', verbose_name='Price level'),
        ),
        migrations.AddField(
            model_name='customerscontacts',
            name='contacttype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.ContactsTypes', verbose_name='Contact Type'),
        ),
        migrations.AddField(
            model_name='customerscontacts',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Customers', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='customersjour',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersJour_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='customersjour',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currenct'),
        ),
        migrations.AddField(
            model_name='customersjour',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersJour_operation', to='inv.Operations', verbose_name='Operation'),
        ),
        migrations.AddField(
            model_name='customersjour',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'RecordStatus'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersJour_Status', to='sy.LookUp', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='customersjour',
            name='statuschangedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By'),
        ),
        migrations.AddField(
            model_name='customersjour',
            name='transtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TransTypes', verbose_name='Trans Type'),
        ),
        migrations.AddField(
            model_name='customersjourline',
            name='accounttype',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('keyid', 90001), ('keyid', 90003), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersJourLine_AccountType', to='sy.LookUp', verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='customersjourline',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersJourLine_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='customersjourline',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersJourLine_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='customersjourline',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersJourLine_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='customersjourline',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersJourLine_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='customersjourline',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currenct'),
        ),
        migrations.AddField(
            model_name='customersjourline',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Customers', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='customersjourline',
            name='customerjour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.CustomersJour', verbose_name='Customer Jour'),
        ),
        migrations.AddField(
            model_name='customersjourline',
            name='ledger',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='Ledger'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='bankdestination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bnk.Banks', verbose_name='Bank Destination'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='bankrefdate',
            field=models.DateField(blank=True, null=True, verbose_name='Bank Reference Date'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='bankrefno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Reference Number'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='beneficiaryname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Beneficiary Name'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='chequebankname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cheque Bank Name'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='chequenumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cheque Number'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPayments_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPayments_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPayments_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPayments_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomersPayments_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='creditcardnumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Credit Card Number'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='creditcardtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.CreditCardsTypes', verbose_name='Credit Card Type'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPayments_Currency', to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Customers', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='cvnumber',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CV Number'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='duedate',
            field=models.DateField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='expiredate',
            field=models.DateField(blank=True, null=True, verbose_name='Expire Date'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='fromaccountno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='From Account NUmber'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='frombankname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='From Bank Name'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='paymentdirection',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'PaymentDirection'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPayments_PaymentDirection', to='sy.LookUp', verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPayments_Paymethod', to='sy.PaymentsMethods', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='remittancedate',
            field=models.DateField(blank=True, null=True, verbose_name='Remittance Date'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='remittanceno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remittance NUmber'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'PaymentStatus'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPayments_Status', to='sy.LookUp', verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='transtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TransTypes', verbose_name='Trans Type'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='treasuryorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TreasuriesOrders', verbose_name='Treasury Order'),
        ),
        migrations.AddField(
            model_name='customerspaymentsline',
            name='accounttype',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'AccountType'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPaymentsLine_accounttype', to='sy.LookUp', verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='customerspaymentsline',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPaymentsLine_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='customerspaymentsline',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPaymentsLine_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='customerspaymentsline',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPaymentsLine_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='customerspaymentsline',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPaymentsLine_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='customerspaymentsline',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Customers', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='customerspaymentsline',
            name='customerpayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.CustomersPayments', verbose_name='Customer Payment'),
        ),
        migrations.AddField(
            model_name='customerspaymentsline',
            name='ledger',
            field=models.ForeignKey(limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPaymentsLine_account', to='gl.Ledger', verbose_name='Ledger'),
        ),
        migrations.AddField(
            model_name='customerstrans',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersTrans_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='customerstrans',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersTrans_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='customerstrans',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersTrans_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='customerstrans',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersTrans_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='customerstrans',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomersTrans_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='customerstrans',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='customerstrans',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersTrans_Customer', to='ar.Customers', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='customerstrans',
            name='customerjour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersTrans_LedgerJour', to='ar.CustomersJour', verbose_name='Customers Jour'),
        ),
        migrations.AddField(
            model_name='customerstrans',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.CustomersPayments', verbose_name='Customers Payment Key'),
        ),
        migrations.AddField(
            model_name='customerstrans',
            name='postby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomersTrans_PostBy', to=settings.AUTH_USER_MODEL, verbose_name='Post By'),
        ),
        migrations.AddField(
            model_name='customerstrans',
            name='transtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TransTypes', verbose_name='Trans Type'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='creditlimit',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Credit Limit'),
        ),
        migrations.AlterField(
            model_name='customersclasses',
            name='creditlimit',
            field=models.DecimalField(decimal_places=12, max_digits=30, null=True, verbose_name='Credit Limit'),
        ),
        migrations.AlterField(
            model_name='customersjour',
            name='currencyrate',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Currenct Rate'),
        ),
        migrations.AlterField(
            model_name='customersjour',
            name='islocked',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Locked'),
        ),
        migrations.AlterField(
            model_name='customersjour',
            name='totalamount',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='customersjourline',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Amount (Debit - Credit)'),
        ),
        migrations.AlterField(
            model_name='customersjourline',
            name='creditamount',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Credit Amount'),
        ),
        migrations.AlterField(
            model_name='customersjourline',
            name='currencyrate',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Currenct Rate'),
        ),
        migrations.AlterField(
            model_name='customersjourline',
            name='debitamount',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Debit Amount'),
        ),
        migrations.AlterField(
            model_name='customersjourline',
            name='qty',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='qty'),
        ),
        migrations.AlterField(
            model_name='customerspayments',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='customerspayments',
            name='currencyrate',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Currenct Rate'),
        ),
        migrations.AlterField(
            model_name='customerspayments',
            name='number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Payment Number'),
        ),
        migrations.AlterField(
            model_name='customerspaymentsline',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='customerspaymentsline',
            name='amountfc',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Amount FC'),
        ),
        migrations.AlterField(
            model_name='customerstrans',
            name='amount',
            field=models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='customerstrans',
            name='amountfc',
            field=models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Amount FC'),
        ),
        migrations.AlterField(
            model_name='customerstrans',
            name='currencyrate',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Currenct Rate'),
        ),
        migrations.AlterField(
            model_name='customerstrans',
            name='settleamount',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Settlement Amount'),
        ),
        migrations.AddField(
            model_name='salesmans',
            name='ledgerdiff',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': 'True'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='Differences Ledger'),
        ),
        migrations.AddField(
            model_name='salesmans',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Salesmans', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='salesmans',
            name='reportingto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Salesmans_ReportingTo', to='ar.Salesmans', verbose_name='Reporting To'),
        ),
        migrations.AddField(
            model_name='salesmans',
            name='salesmangroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.SalesmansGroups', verbose_name='Salesman Group'),
        ),
        migrations.AddField(
            model_name='salesmans',
            name='status',
            field=models.ForeignKey(limit_choices_to={'keyname': 'AccountStatus'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Salesmans_status', to='sy.LookUp', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='salesmans',
            name='statuschangedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Salesmans_statuschangedby', to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By'),
        ),
        migrations.AddField(
            model_name='salesmans',
            name='treasurylink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Treasuries', verbose_name='Treasury Link'),
        ),
        migrations.AddField(
            model_name='salesmans',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='drawerslogcloseline',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='drawerslogcloseline',
            name='drawerlogclose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DrawersLogCloseline_drawerlogclose', to='ar.DrawersLogClose', verbose_name='Drawer Log Close'),
        ),
        migrations.AddField(
            model_name='drawerslogcloseline',
            name='paymethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DrawersLogCloseline_paymethod', to='sy.PaymentsMethods', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='drawerslogclose',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DrawersLogClose_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='drawerslogclose',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DrawersLogClose_treasury', to='gl.Treasuries', verbose_name='Treasury'),
        ),
        migrations.AddField(
            model_name='drawerslogclose',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DrawersLogClose_user', to=settings.AUTH_USER_MODEL, verbose_name='User '),
        ),
        migrations.AddField(
            model_name='drawerslog',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DrawersLog_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='drawerslog',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='drawerslog',
            name='drawerlogclose',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.DrawersLogClose', verbose_name='Drawer Log Close'),
        ),
        migrations.AddField(
            model_name='drawerslog',
            name='paymethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DrawersLog_paymethod', to='sy.PaymentsMethods', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='drawerslog',
            name='salesman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='DrawersLog_salesman', to='ar.Salesmans', verbose_name='Salesman'),
        ),
        migrations.AddField(
            model_name='drawerslog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DrawersLog_user', to=settings.AUTH_USER_MODEL, verbose_name='User '),
        ),
        migrations.AddField(
            model_name='customerspaymentsschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomersPaymentsSchedule_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='customerspaymentsschedule',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='customerspaymentsschedule',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPaymentsSchedule_Customer', to='ar.Customers', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='customerspaymentsschedule',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inv.Operations', verbose_name='Operation'),
        ),
        migrations.AddField(
            model_name='customerspaymentsschedule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersPaymentsSchedule_parent', to='ar.CustomersPaymentsSchedule', verbose_name='Parent Rec ID'),
        ),
        migrations.AddField(
            model_name='customerspaymentsschedule',
            name='paymenttearm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.PaymentsTearms', verbose_name='Payment Tearm'),
        ),
        migrations.AddField(
            model_name='collectionsduepayments',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Collections', verbose_name='Collection'),
        ),
        migrations.AddField(
            model_name='collectionsduepayments',
            name='customerpaymentschedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.CustomersPaymentsSchedule', verbose_name='Due Payment'),
        ),
        migrations.AddField(
            model_name='collections',
            name='bankchequedestination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Collections_bankchequedestination', to='bnk.Banks', verbose_name='Bank Cheque Destination'),
        ),
        migrations.AddField(
            model_name='collections',
            name='bankdestination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Collections_bankdestination', to='bnk.Banks', verbose_name='Bank Remittance Destination'),
        ),
        migrations.AddField(
            model_name='collections',
            name='bankdocunderprocess',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bnk.BanksDocumentsUnderProcess', verbose_name='Bank Doc. Under Process'),
        ),
        migrations.AddField(
            model_name='collections',
            name='collector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Salesmans', verbose_name='Collector'),
        ),
        migrations.AddField(
            model_name='collections',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Collections_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='collections',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Collections_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='collections',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Collections_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='collections',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Collections_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='collections',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Collections_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='collections',
            name='creditcardtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.CreditCardsTypes', verbose_name='Credit Card Type'),
        ),
        migrations.AddField(
            model_name='collections',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Collections_Currency', to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='collections',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Customers', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='collections',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Collections_Paymethod', to='sy.PaymentsMethods', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='collections',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'RecordStatus'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Collections_Status', to='sy.LookUp', verbose_name='Collection Status'),
        ),
        migrations.AddField(
            model_name='collections',
            name='statuschangedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By'),
        ),
        migrations.AddField(
            model_name='customers',
            name='salesperson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Salesmans', verbose_name='Salesman'),
        ),
        migrations.AddField(
            model_name='customersclasses',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Salesmans', verbose_name='Salesman'),
        ),
        migrations.AddField(
            model_name='customerspayments',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Collections', verbose_name='Collection'),
        ),
    ]
