# Generated by Django 2.0.9 on 2021-05-29 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCostBalances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(blank=True, null=True, unique=True, verbose_name='serial')),
                ('fiscalyearperiod', models.IntegerField(blank=True, null=True, verbose_name='Fiscal Year Period')),
                ('dramount', models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True, verbose_name='Debit Amount')),
                ('cramount', models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True, verbose_name='Credit Amount')),
                ('dramountfc', models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True, verbose_name='Debit Amount FC')),
                ('cramountfc', models.DecimalField(blank=True, decimal_places=3, max_digits=30, null=True, verbose_name='Credit Amount FC')),
                ('lastcustomertrans', models.IntegerField(blank=True, null=True, verbose_name='Last Customer Trans')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('shortengname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Eng Name')),
                ('shortarbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Arb Name')),
                ('startbusinessdate', models.DateField(blank=True, null=True, verbose_name='Start Business Date')),
                ('statusdate', models.DateField(blank=True, null=True, verbose_name='Status Date')),
                ('statusreason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Reason')),
                ('creditlimit', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Credit Limit')),
                ('creditdays', models.PositiveIntegerField(blank=True, null=True, verbose_name='Credit Days')),
                ('mandatorycreditlimit', models.BooleanField(default=False, verbose_name='Mandatory Credit Limit')),
                ('allowtarget', models.BooleanField(default=False, verbose_name='Allow Target')),
                ('noofemployees', models.PositiveIntegerField(blank=True, null=True, verbose_name='No Of Employees')),
                ('vatgroup', models.PositiveIntegerField(blank=True, null=True, verbose_name='VAT Group')),
                ('vatregnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='VAT Registration Number')),
                ('iscash', models.BooleanField(default=False, verbose_name='Is Cash Customer')),
                ('iscredit', models.BooleanField(default=False, verbose_name='Is Credit Customer')),
                ('allowaccountentry', models.BooleanField(default=False, verbose_name='Allow Account Entry')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CustomersAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2')),
                ('address3', models.CharField(blank=True, max_length=100, null=True, verbose_name='address 3')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('latitudes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitudes')),
                ('longitudes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitudes')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CustomersCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CustomersClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, null=True, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('isdefault', models.BooleanField(default=False, verbose_name='Is Default')),
                ('creditlimit', models.DecimalField(decimal_places=1, max_digits=12, null=True, verbose_name='Credit Limit')),
                ('creditdays', models.PositiveIntegerField(null=True, verbose_name='Credit Days')),
                ('allowchaneged', models.BooleanField(verbose_name='Allow Change Class info')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CustomersContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('value', models.CharField(max_length=300, verbose_name='Value')),
                ('inactive', models.BooleanField(verbose_name='Inactive')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CustomersJour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journalnumber', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Journal Number')),
                ('journaldate', models.DateField(blank=True, null=True, verbose_name='Journal Date')),
                ('journalyear', models.CharField(blank=True, max_length=4, null=True, verbose_name='Journal Year')),
                ('journalmonth', models.CharField(blank=True, max_length=2, null=True, verbose_name='Journal Month')),
                ('sequence', models.IntegerField(blank=True, null=True, verbose_name='Sequence')),
                ('reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference')),
                ('reference1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference1')),
                ('reference2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reference1')),
                ('islocked', models.BooleanField(default=False, verbose_name='Is Locked')),
                ('totalamount', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Total Amount')),
                ('currencyrate', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Currenct Rate')),
                ('paymentid', models.IntegerField(blank=True, null=True, verbose_name='Customer Payment ID')),
                ('fiscalyearperiod', models.IntegerField(blank=True, null=True, verbose_name='Fiscal Year Period')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('confirmdate', models.DateField(blank=True, null=True, verbose_name='Confirm Date')),
                ('postdate', models.DateField(blank=True, null=True, verbose_name='Post Date')),
                ('statusdate', models.DateField(blank=True, null=True, verbose_name='Status Date')),
                ('statusreason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Reason')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Created Date')),
                ('itemtransid', models.IntegerField(blank=True, null=True, verbose_name='Item Trans ID')),
            ],
            options={
                'ordering': ['journalnumber'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CustomersJourLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('engdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='Eng Description')),
                ('arbdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='Arb Description')),
                ('qty', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='qty')),
                ('currencyrate', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Currenct Rate')),
                ('reverse', models.IntegerField(blank=True, null=True, verbose_name='Reverse')),
                ('debitamount', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Debit Amount')),
                ('creditamount', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Credit Amount')),
                ('amount', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Amount (Debit - Credit)')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CustomersPayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Payment Number')),
                ('paymentdate', models.DateTimeField(blank=True, null=True, verbose_name='Payment Date')),
                ('fiscalyearperiod', models.IntegerField(blank=True, null=True, verbose_name='Fiscal Year Period')),
                ('amount', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Amount')),
                ('isposted', models.BooleanField(verbose_name='Is Posted')),
                ('postdate', models.DateTimeField(blank=True, null=True, verbose_name='Post Date')),
                ('currencyrate', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Currenct Rate')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CustomersPaymentsLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('amount', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Amount')),
                ('amountfc', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Amount FC')),
                ('engdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='Eng Description')),
                ('arbdesc', models.CharField(blank=True, max_length=256, null=True, verbose_name='Arb Description')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CustomersTrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transdate', models.DateField(blank=True, null=True, verbose_name='Trans Date')),
                ('docnumber', models.CharField(max_length=50, verbose_name='Doc Number')),
                ('vendortrans', models.IntegerField(blank=True, null=True, verbose_name='Vendor Trans')),
                ('operationid', models.IntegerField(blank=True, null=True, verbose_name='Operation ID')),
                ('customertrans', models.IntegerField(blank=True, null=True, verbose_name='Customer Trans')),
                ('engdesc', models.CharField(max_length=100, verbose_name='Eng Desc')),
                ('arbdesc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Desc')),
                ('amount', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Amount')),
                ('amountfc', models.DecimalField(decimal_places=1, max_digits=12, verbose_name='Amount FC')),
                ('currencyrate', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Currenct Rate')),
                ('duedate', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('closedate', models.DateField(blank=True, null=True, verbose_name='Close Date')),
                ('approvaldate', models.DateTimeField(blank=True, null=True, verbose_name='Approval Date')),
                ('postdate', models.DateTimeField(blank=True, null=True, verbose_name='Post Date')),
                ('fiscalyearperiod', models.IntegerField(blank=True, null=True, verbose_name='Fiscal Year Period')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('settleamount', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Settlement Amount')),
                ('lastsettledate', models.DateTimeField(blank=True, null=True, verbose_name='Last Settle Date')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Created Date')),
                ('approvalby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomersTrans_approvalby', to=settings.AUTH_USER_MODEL, verbose_name='Approval By')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='VisitsClasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('noofvisit', models.PositiveIntegerField(blank=True, null=True, verbose_name='No Of Visits')),
                ('visitperiodminute', models.PositiveIntegerField(blank=True, null=True, verbose_name='Visits Period Per minute')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
