# Generated by Django 2.2 on 2021-09-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl', '0001_initial'),
        ('sy', '0001_initial'),
        ('ar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Collection Number')),
                ('collectiondate', models.DateField(blank=True, null=True, verbose_name='Collection Date')),
                ('statusdate', models.DateField(blank=True, null=True, verbose_name='status Date')),
                ('statusreason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Reason')),
                ('amount', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Amount')),
                ('currencyrate', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Currenct Rate')),
                ('chequenumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cheque Number')),
                ('chequebankname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cheque Bank Name')),
                ('duedate', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('beneficiaryname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Beneficiary Name')),
                ('remittanceno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remittance NUmber')),
                ('fromaccountno', models.CharField(blank=True, max_length=100, null=True, verbose_name='From Account NUmber')),
                ('frombankname', models.CharField(blank=True, max_length=100, null=True, verbose_name='From Bank Name')),
                ('remittancedate', models.DateField(blank=True, null=True, verbose_name='Remittance Date')),
                ('creditcardnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Credit Card Number')),
                ('cvnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='CV Number')),
                ('expiredate', models.DateField(blank=True, null=True, verbose_name='Expire Date')),
                ('bankrefno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Reference Number')),
                ('bankrefdate', models.DateField(blank=True, null=True, verbose_name='Bank Reference Date')),
                ('isclose', models.BooleanField(blank=True, default=False, verbose_name='Is Close')),
                ('islocked', models.BooleanField(default=False, verbose_name='Is IsLocked')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CollectionsDuePayments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationnumber', models.CharField(blank=True, max_length=20, null=True, verbose_name='Number')),
                ('duedate', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('dueamount', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Due Amount')),
                ('paidamount', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Paid Amount')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CustomersPaymentsSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operationdate', models.DateField(blank=True, null=True, verbose_name='Operation Date')),
                ('operationamount', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Operation Amount')),
                ('operationamountfc', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Operation Amount FC')),
                ('duedate', models.DateField(blank=True, null=True, verbose_name='Due Date')),
                ('dueamount', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Due Amount')),
                ('dueamountfc', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Due Amount FC')),
                ('paidamount', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Paid Amount')),
                ('currencyrate', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Currenct Rate')),
                ('isclose', models.BooleanField(default=False, verbose_name='Is Close')),
                ('created_date', models.DateTimeField(blank=True, null=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='DrawersLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcename', models.CharField(max_length=100, verbose_name='Source Name')),
                ('sourcerecid', models.IntegerField(blank=True, null=True, verbose_name='Source Record ID')),
                ('currencyrate', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Currenct Rate')),
                ('actioncode', models.CharField(max_length=20, verbose_name='Action Code')),
                ('amount', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Amount')),
                ('actiondate', models.CharField(blank=True, max_length=10, null=True, verbose_name='Action Date')),
                ('actiontime', models.CharField(blank=True, max_length=8, null=True, verbose_name='Action Time')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='DrawersLogClose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closedate', models.DateField(blank=True, null=True, verbose_name='Close Date')),
                ('closetime', models.TimeField(blank=True, null=True, verbose_name='Close Time')),
                ('todrawerlog', models.IntegerField(blank=True, null=True, verbose_name='Last ID Close from Drawer Log')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='DrawersLogCloseline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyrate', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Currenct Rate')),
                ('calcamount', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Calculated Amount')),
                ('actamount', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Actual Amount')),
                ('diffamount', models.DecimalField(decimal_places=12, max_digits=30, verbose_name='Diff. Amount')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Salesmans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('iscashier', models.BooleanField(default=False, verbose_name='Is Cashier')),
                ('iscollector', models.BooleanField(default=False, verbose_name='Is Collector')),
                ('statusdate', models.DateField(blank=True, null=True, verbose_name='Status Date')),
                ('statusreason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Reason')),
                ('mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile')),
                ('noofvisitperday', models.PositiveIntegerField(blank=True, null=True, verbose_name='No Of Visit Per Day')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='SalesmansGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='customercostbalances',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersCostBalances_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='customercostbalances',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersCostBalances_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='customercostbalances',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersCostBalances_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='customercostbalances',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersCostBalances_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='customercostbalances',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Customers', verbose_name='Customer'),
        ),
        migrations.AddField(
            model_name='customers',
            name='accountsize',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'AccountSize'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_accountsize', to='sy.LookUp', verbose_name='Account Size'),
        ),
        migrations.AddField(
            model_name='customers',
            name='agingstyle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.AgingStyles', verbose_name='Aging Style'),
        ),
        migrations.AddField(
            model_name='customers',
            name='allowcashdiscount',
            field=models.BooleanField(default=False, verbose_name='Allow Cash Discount'),
        ),
        migrations.AddField(
            model_name='customers',
            name='arledger',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': 'True'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='AR. Ledger'),
        ),
        migrations.AddField(
            model_name='customers',
            name='businessactivitytype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.BusinessActivitiesTypes', verbose_name='Business Activity Type'),
        ),
    ]
