# Generated by Django 2.0.9 on 2021-05-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('datasource', models.CharField(max_length=100, verbose_name='Data Source')),
                ('isprocedure', models.BooleanField(verbose_name='Is Stored Procedure')),
                ('josndesign', models.CharField(max_length=1000000, verbose_name='JOSN Design')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ReportsGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rp.ReportsGroups', verbose_name='Parent')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ReportsParameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fieldname', models.CharField(max_length=60, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('datatype', models.CharField(blank=True, max_length=100, null=True, verbose_name='Data Type')),
                ('controltype', models.CharField(blank=True, max_length=100, null=True, verbose_name='Control Type')),
                ('isdisable', models.BooleanField(verbose_name='Is Disable')),
                ('canprint', models.BooleanField(default=False, verbose_name='Can Print')),
                ('defaultvalue', models.CharField(blank=True, default='%', max_length=1000, null=True, verbose_name='Default Value')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rp.Reports', verbose_name='Report')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='reports',
            name='reportgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='rp.ReportsGroups', verbose_name='Report Group'),
        ),
        migrations.AlterUniqueTogether(
            name='reportsparameters',
            unique_together={('fieldname', 'report')},
        ),
    ]
