# Generated by Django 2.2 on 2021-09-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='isdashboard',
            field=models.BooleanField(default=False, verbose_name='Is Dashboard'),
        ),
        migrations.AddField(
            model_name='reportsparameters',
            name='isvisible',
            field=models.BooleanField(default=True, verbose_name='Is Visible'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='arbname',
            field=models.CharField(max_length=100, null=True, verbose_name='Arb Name'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='datasource',
            field=models.CharField(max_length=100, null=True, verbose_name='Data Source'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='engname',
            field=models.CharField(max_length=100, null=True, verbose_name='Eng Name'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='isprocedure',
            field=models.BooleanField(default=False, verbose_name='Is Stored Procedure'),
        ),
        migrations.AlterField(
            model_name='reports',
            name='josndesign',
            field=models.CharField(max_length=1000000, null=True, verbose_name='JOSN Design'),
        ),
        migrations.AlterField(
            model_name='reportsparameters',
            name='engname',
            field=models.CharField(max_length=100, null=True, verbose_name='Eng Name'),
        ),
        migrations.AlterField(
            model_name='reportsparameters',
            name='isdisable',
            field=models.BooleanField(default=False, verbose_name='Is Disable'),
        ),
    ]
