# Generated by Django 2.0.9 on 2021-05-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gl', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='vwPeriodsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddressesTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='AgingStyles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('isdefault', models.BooleanField(default=False, verbose_name='Is Default')),
                ('useduedate', models.BooleanField(default=False, verbose_name='Use Due Date')),
                ('remarks', models.CharField(max_length=100, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='AgingStylesLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('periodvalue', models.IntegerField(blank=True, null=True, verbose_name='Period Value Per Days')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('agingstyle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.AgingStyles', verbose_name='Module')),
            ],
            options={
                'ordering': ['rank'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('isheadoffice', models.BooleanField(default=False, verbose_name='Is Head Office')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2')),
                ('address3', models.CharField(blank=True, max_length=100, null=True, verbose_name='address 3')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('latitudes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitudes')),
                ('longitudes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitudes')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='BranchesContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('value', models.CharField(max_length=300, verbose_name='Value')),
                ('inactive', models.BooleanField(verbose_name='Inactive')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='BranchesDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessActivitiesTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Areas', verbose_name='Area')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('prefix', models.CharField(max_length=50, verbose_name='Prefix')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('ishijri', models.BooleanField(default=False, verbose_name='Is Hijri Date')),
                ('logo', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/', verbose_name='Company Logo')),
                ('taxregisterno', models.CharField(max_length=50, verbose_name='Tax Register Number')),
                ('allowed_users', models.PositiveIntegerField(blank=True, null=True, verbose_name='users')),
                ('usecostcenter1', models.BooleanField(default=False, verbose_name='User Cost Center 1')),
                ('usecostcenter2', models.BooleanField(default=False, verbose_name='User Cost Center 2')),
                ('usecostcenter3', models.BooleanField(default=False, verbose_name='User Cost Center 3')),
                ('usecostcenter4', models.BooleanField(default=False, verbose_name='User Cost Center 4')),
                ('capitalledger', models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': 'True'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compayprofile_capitalledger', to='gl.Ledger', verbose_name='Capital Ledger')),
                ('defaultcurrency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compayprofile_currency', to='crm.Currency', verbose_name='Default Curency')),
                ('plledger', models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': 'True'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compayprofile_plledger', to='gl.Ledger', verbose_name='P & L Ledger')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CompanyProfileAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2')),
                ('address3', models.CharField(blank=True, max_length=100, null=True, verbose_name='address 3')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('latitudes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitudes')),
                ('longitudes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitudes')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('addresstype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.AddressesTypes', verbose_name='Address Type')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Cities', verbose_name='City')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.CompanyProfile', verbose_name='Company')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CompanyProfileContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('value', models.CharField(max_length=300, verbose_name='Value')),
                ('inactive', models.BooleanField(verbose_name='Inactive')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.CompanyProfile', verbose_name='Company')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CompanyProfileDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Document Number')),
                ('issuedate', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiredate', models.DateField(blank=True, null=True, verbose_name='Expire Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.CompanyProfile', verbose_name='Company')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='ContactsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CreditCardsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.Departments', verbose_name='Parent')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.Cities', verbose_name='Cities')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='DocumentsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='FiscalYears',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='FiscalYearsPeriods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('fromdate', models.DateField(verbose_name='From Date')),
                ('todate', models.DateField(verbose_name='To Date')),
                ('rank', models.IntegerField(blank=True, null=True, verbose_name='Rank')),
                ('fiscalyear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.FiscalYears', verbose_name='Fiscal Year')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='FiscalYearsPeriodsModules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opendate', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('closedate', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('fiscalyearperiod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.FiscalYearsPeriods', verbose_name='Fiscal Year Period')),
            ],
            options={
                'ordering': ['-pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='LookUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyid', models.IntegerField(unique=True, verbose_name='Key ID')),
                ('keyname', models.CharField(max_length=100, verbose_name='Key Name')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('value', models.CharField(blank=True, max_length=200, null=True, verbose_name='Value')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('isregistered', models.BooleanField(default=False, verbose_name='Is Registered')),
                ('isfydependant', models.BooleanField(default=False, verbose_name='Is Fiscal Year Dependant')),
                ('isgl', models.BooleanField(default=False, verbose_name='Is General Ledger')),
                ('isar', models.BooleanField(default=False, verbose_name='Is Account Receivable')),
                ('isap', models.BooleanField(default=False, verbose_name='Is Account Payable')),
                ('isfa', models.BooleanField(default=False, verbose_name='Is Fixed Assets')),
                ('isin', models.BooleanField(default=False, verbose_name='Is Inventory')),
                ('ishr', models.BooleanField(default=False, verbose_name='Is Human Resources')),
                ('isfc', models.BooleanField(default=False, verbose_name='Is Manufacturing')),
                ('ispm', models.BooleanField(default=False, verbose_name='Is Projects Management')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Nationalities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PaymentsMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('iscash', models.BooleanField(default=False, verbose_name='Is Cash')),
                ('iscreditcard', models.BooleanField(default=False, verbose_name='Is Credit Card')),
                ('ischeck', models.BooleanField(default=False, verbose_name='Is Check')),
                ('iscredit', models.BooleanField(default=False, verbose_name='Is Credit')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PaymentsTearms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('remarks', models.CharField(max_length=100, verbose_name='Remarks')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.Modules', verbose_name='Modules')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PaymentsTearmsLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessthandays', models.IntegerField(blank=True, null=True, verbose_name='Less Than Days')),
                ('discountper', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True, verbose_name='Discount Percent')),
                ('paymentmethod', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.PaymentsMethods', verbose_name='Payment Methods')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='PriceLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code')),
                ('engname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('inactive', models.BooleanField(verbose_name='Inactive')),
                ('isminprice', models.BooleanField(verbose_name='Is Minimum Price')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Modules', verbose_name='Module')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Taxes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code')),
                ('engname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('taxledger', models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Taxes_taxledger', to='gl.Ledger', verbose_name='Tax Ledger')),
                ('taxsettledledger', models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Taxes_taxsettledledger', to='gl.Ledger', verbose_name='Tax Settled Ledger')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='TaxesGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code')),
                ('engname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='TaxesGroupsLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromdate', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('todate', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Taxes', verbose_name='Tax')),
                ('taxgroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.TaxesGroups', verbose_name='Tax Group')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='TaxesLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Tax Value Percent')),
                ('limitmin', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Tax Limit Min')),
                ('limitmax', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Tax Limit Max')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('tax', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Taxes', verbose_name='Tax')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='fiscalyearsperiodsmodules',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Modules', verbose_name='Module'),
        ),
        migrations.AddField(
            model_name='fiscalyearsperiods',
            name='periodtype',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'PeriodType'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.LookUp', verbose_name='Period  Type'),
        ),
        migrations.AddField(
            model_name='countries',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Nationalities', verbose_name='Nationality'),
        ),
        migrations.AddField(
            model_name='countries',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Regions', verbose_name='Regions'),
        ),
        migrations.AddField(
            model_name='companyprofiledocuments',
            name='documenttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.DocumentsTypes', verbose_name='Document Type'),
        ),
        migrations.AddField(
            model_name='companyprofilecontacts',
            name='contacttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.ContactsTypes', verbose_name='Contact Type'),
        ),
        migrations.AddField(
            model_name='companyprofileaddresses',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Countries', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='companyprofileaddresses',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Districts', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.Countries', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='branchesdepartments',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BranchesDepartments_Branch', to='sy.Departments', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='branchesdepartments',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='BranchesDepartments_Department', to='sy.Departments', verbose_name='Department'),
        ),
        migrations.AddField(
            model_name='branchescontacts',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.CompanyProfile', verbose_name='Branch'),
        ),
        migrations.AddField(
            model_name='branchescontacts',
            name='contacttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.ContactsTypes', verbose_name='Contact Type'),
        ),
        migrations.AddField(
            model_name='branches',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Cities', verbose_name='City'),
        ),
        migrations.AddField(
            model_name='branches',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.CompanyProfile', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='branches',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Countries', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='branches',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Districts', verbose_name='District'),
        ),
        migrations.AddField(
            model_name='branches',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.Branches', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='branches',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Treasuries', verbose_name='Treasury'),
        ),
        migrations.AddField(
            model_name='areas',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.Countries', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='agingstyles',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sy.Modules', verbose_name='Module'),
        ),
    ]
