# Generated by Django 2.2 on 2021-09-29 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gl', '0002_auto_20210929_1512'),
        ('sy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashDiscountsRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, verbose_name='Eng Name')),
                ('arbname', models.CharField(max_length=100, verbose_name='Arb Name')),
                ('accounttype', models.ForeignKey(blank=True, limit_choices_to={'keyname': 'AccountType'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CashDiscountsRoles_AccountType', to='sy.LookUp', verbose_name='Account Type')),
                ('ledger', models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='Ledger')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='CashDiscountsRolesLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessthanpercent', models.IntegerField(blank=True, null=True, verbose_name='Less Than Pecent From Credit Period')),
                ('discountpercent', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Discount Percent')),
                ('cashdiscountrole', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.CashDiscountsRoles', verbose_name='Cash Discount Role')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='StatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablename', models.CharField(blank=True, max_length=100, null=True, verbose_name='Table Name')),
                ('recordid', models.IntegerField(blank=True, null=True, verbose_name='Record ID')),
                ('statusdate', models.DateField(blank=True, null=True, verbose_name='Status Date')),
                ('statusreason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Reason')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='StatusLog_Status', to='sy.LookUp', verbose_name='Status')),
                ('statuschangedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By')),
            ],
            options={
                'ordering': ['-pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.RemoveField(
            model_name='paymentstearms',
            name='module',
        ),
        migrations.AddField(
            model_name='paymentsmethods',
            name='isremittance',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Remittance'),
        ),
        migrations.AddField(
            model_name='paymentstearms',
            name='accountcheck',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'AccountCheck'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PaymentsTearms_accountcheck', to='sy.LookUp', verbose_name='Account Checking Type'),
        ),
        migrations.AddField(
            model_name='paymentstearms',
            name='accounttype',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'AccountType'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PaymentsTearms_AccountType', to='sy.LookUp', verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='paymentstearms',
            name='allowcashdiscount',
            field=models.BooleanField(default=False, verbose_name='Allow cash Discount Role'),
        ),
        migrations.AddField(
            model_name='paymentstearms',
            name='creditdays',
            field=models.PositiveIntegerField(null=True, verbose_name='Credit Days'),
        ),
        migrations.AddField(
            model_name='paymentstearms',
            name='creditlimit',
            field=models.DecimalField(decimal_places=12, max_digits=30, null=True, verbose_name='Credit Limit'),
        ),
        migrations.AddField(
            model_name='paymentstearms',
            name='isperiod',
            field=models.BooleanField(default=False, verbose_name='Is Period Begin Month'),
        ),
        migrations.AddField(
            model_name='paymentstearms',
            name='noofpayment',
            field=models.PositiveIntegerField(null=True, verbose_name='No Of Payments'),
        ),
        migrations.AddField(
            model_name='paymentstearms',
            name='paymentintervalday',
            field=models.PositiveIntegerField(null=True, verbose_name='Payment Interval Per Day'),
        ),
        migrations.AddField(
            model_name='paymentstearms',
            name='perioddays',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Period Days'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.CompanyProfile', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Branches', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='isap',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Account Payable'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='isar',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Account Receivable'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='isfa',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Fixed Assets'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='isfc',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Manufacturing'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='isfydependant',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Fiscal Year Dependant'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='isgl',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is General Ledger'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='ishr',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Human Resources'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='isin',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Inventory'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='ispm',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Projects Management'),
        ),
        migrations.AlterField(
            model_name='modules',
            name='isregistered',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Registered'),
        ),
        migrations.AlterField(
            model_name='paymentsmethods',
            name='iscash',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Cash'),
        ),
        migrations.AlterField(
            model_name='paymentsmethods',
            name='ischeck',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Check'),
        ),
        migrations.AlterField(
            model_name='paymentsmethods',
            name='iscredit',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Credit'),
        ),
        migrations.AlterField(
            model_name='paymentsmethods',
            name='iscreditcard',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Credit Card'),
        ),
        migrations.AlterField(
            model_name='paymentstearms',
            name='arbname',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name'),
        ),
        migrations.AlterField(
            model_name='paymentstearms',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks'),
        ),
        migrations.DeleteModel(
            name='PaymentsTearmsLine',
        ),
    ]
