# Generated by Django 2.2.3 on 2022-03-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sy', '0002_auto_20210929_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyearsperiodsmodules',
            name='closedate',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalyearsperiodsmodules',
            name='opendate',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
