# Generated by Django 2.2.3 on 2022-03-30 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sy', '0005_auto_20220328_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdiscountsroles',
            name='accounttype',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('keyid', 90015), ('keyid', 90002), ('keyid', 90003), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CashDiscountsRoles_AccountType', to='sy.LookUp', verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='paymentstearms',
            name='accounttype',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('keyid', 90015), ('keyid', 90002), ('keyid', 90003), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='PaymentsTearms_AccountType', to='sy.LookUp', verbose_name='Account Type'),
        ),
    ]
