# Generated by Django 2.2 on 2021-09-29 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20210929_1512'),
        ('ar', '0002_auto_20210929_1512'),
        ('sy', '0001_initial'),
        ('inv', '0002_auto_20210929_1512'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ap', '0002_auto_20210929_1512'),
        ('gl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costcategories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.CostCategories', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='costcenters',
            name='costcentercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.CostCategories', verbose_name='Cost Category'),
        ),
        migrations.AddField(
            model_name='costcenters',
            name='costcenterlevel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.CostCentersLevels', verbose_name='Cost Center Level'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledgercategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.LedgersCategories', verbose_name='Ledger Category'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledgerclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.LedgersClasses', verbose_name='Ledger Classes'),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledgertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.LedgersTypes', verbose_name='Ledger Type'),
        ),
        migrations.AddField(
            model_name='ledgercostbalances',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerCostBalances_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='ledgercostbalances',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerCostBalances_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='ledgercostbalances',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerCostBalances_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='ledgercostbalances',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerCostBalances_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='ledgercostbalances',
            name='ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='ledger'),
        ),
        migrations.AddField(
            model_name='ledgerjour',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LedgerJour_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ledgerjour',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currenct'),
        ),
        migrations.AddField(
            model_name='ledgerjour',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerJour_operation', to='inv.Operations', verbose_name='Operation'),
        ),
        migrations.AddField(
            model_name='ledgerjour',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'RecordStatus'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerJour_Status', to='sy.LookUp', verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='ledgerjour',
            name='statuschangedby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By'),
        ),
        migrations.AddField(
            model_name='ledgerjour',
            name='statusdate',
            field=models.DateField(blank=True, null=True, verbose_name='Status Date'),
        ),
        migrations.AddField(
            model_name='ledgerjour',
            name='statusreason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Reason'),
        ),
        migrations.AddField(
            model_name='ledgerjour',
            name='transtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TransTypes', verbose_name='Trans Type'),
        ),
        migrations.AddField(
            model_name='ledgerjourline',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerJourLine_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='ledgerjourline',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerJourLine_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='ledgerjourline',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerJourLine_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='ledgerjourline',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerJourLine_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='ledgerjourline',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currenct'),
        ),
        migrations.AddField(
            model_name='ledgerjourline',
            name='ledger',
            field=models.ForeignKey(limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='Ledger'),
        ),
        migrations.AddField(
            model_name='ledgerjourline',
            name='ledgerjour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.LedgerJour', verbose_name='Ledger Jour'),
        ),
        migrations.AddField(
            model_name='ledgerpayments',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPayments_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='ledgerpayments',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPayments_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='ledgerpayments',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPayments_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='ledgerpayments',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPayments_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='ledgerpayments',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LedgerPayments_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ledgerpayments',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPayments_Currency', to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='ledgerpayments',
            name='ledger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='ledger'),
        ),
        migrations.AddField(
            model_name='ledgerpayments',
            name='paymentdirection',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'PaymentDirection'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPayments_PaymentDirection', to='sy.LookUp', verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='ledgerpayments',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPayments_Paymethod', to='sy.PaymentsMethods', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='ledgerpayments',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'PaymentStatus'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPayments_Status', to='sy.LookUp', verbose_name='Payment Status'),
        ),
        migrations.AddField(
            model_name='ledgerpayments',
            name='transtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TransTypes', verbose_name='Trans Type'),
        ),
        migrations.AddField(
            model_name='ledgerpayments',
            name='treasuryorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TreasuriesOrders', verbose_name='Treasury Order'),
        ),
        migrations.AddField(
            model_name='ledgerpaymentsline',
            name='account',
            field=models.ForeignKey(limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPaymentsLine_account', to='gl.Ledger', verbose_name='Ledger'),
        ),
        migrations.AddField(
            model_name='ledgerpaymentsline',
            name='accounttype',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'AccountType'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPaymentsLine_accounttype', to='sy.LookUp', verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='ledgerpaymentsline',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPaymentsLine_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='ledgerpaymentsline',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPaymentsLine_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='ledgerpaymentsline',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPaymentsLine_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='ledgerpaymentsline',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='LedgerPaymentsLine_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='ledgerpaymentsline',
            name='ledger',
            field=models.ForeignKey(limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='Ledger'),
        ),
        migrations.AddField(
            model_name='ledgerpaymentsline',
            name='ledgerpayment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.LedgerPayments', verbose_name='Ledger Payment'),
        ),
        migrations.AddField(
            model_name='ledgerscategories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.LedgersCategories', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='ledgersclasses',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.LedgersClasses', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='approvalby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LedgerTrans_approvalby', to=settings.AUTH_USER_MODEL, verbose_name='Approval By'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransLedger_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransLedger_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransLedger_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransLedger_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LedgerTrans_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransLedger_Ledger', to='gl.Ledger', verbose_name='Ledger'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='ledgerjour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransLedger_LedgerJour', to='gl.LedgerJour', verbose_name='Ledger Jour'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='operation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='CustomersTrans_operation', to='inv.Operations', verbose_name='Operation'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.LedgerPayments', verbose_name='Ledger Payment Key'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='postby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LedgerTrans_PostBy', to=settings.AUTH_USER_MODEL, verbose_name='Post By'),
        ),
        migrations.AddField(
            model_name='ledgertrans',
            name='transtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TransTypes', verbose_name='Trans Type'),
        ),
        migrations.AddField(
            model_name='taxestrans',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TaxesTrans_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='taxestrans',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TaxesTrans_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='taxestrans',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TaxesTrans_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='taxestrans',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TaxesTrans_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='taxestrans',
            name='ledger',
            field=models.ForeignKey(limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='Ledger'),
        ),
        migrations.AddField(
            model_name='taxestrans',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TaxesTrans_tax', to='sy.Taxes', verbose_name='Tax'),
        ),
        migrations.AddField(
            model_name='taxestrans',
            name='transtype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TransTypes', verbose_name='Trans Type'),
        ),
        migrations.AddField(
            model_name='transtypes',
            name='paymentdirection',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'PaymentDirection'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransTypes_PaymentDirection', to='sy.LookUp', verbose_name='Payment Direction'),
        ),
        migrations.AddField(
            model_name='transtypes',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransTypes_PaymentMethod', to='sy.PaymentsMethods', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='transtypes',
            name='sign',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'Sign'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransTypes_Sign', to='sy.LookUp', verbose_name='Sign'),
        ),
        migrations.AddField(
            model_name='transtypes',
            name='transkind',
            field=models.ForeignKey(limit_choices_to={'keyname': 'TransKind'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransTypes_TransKind', to='sy.LookUp', verbose_name='Trans Kind'),
        ),
        migrations.AddField(
            model_name='treasuries',
            name='ledgerdiff',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': 'True'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='Differences Ledger'),
        ),
        migrations.AddField(
            model_name='treasuries',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Treasuries', verbose_name='Parent'),
        ),
        migrations.AddField(
            model_name='treasuries',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='treasuriesaccounts',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesAccounts_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='treasuriesaccounts',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesAccounts_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='treasuriesaccounts',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesAccounts_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='treasuriesaccounts',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesAccounts_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='treasuriesaccounts',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='ledger'),
        ),
        migrations.AddField(
            model_name='treasuriesaccounts',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Treasuries', verbose_name='treasury'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='accounttype',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'AccountType'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesOrders_AccountType', to='sy.LookUp', verbose_name='Account Type'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='approvalby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TreasuriesOrders_approvalby', to=settings.AUTH_USER_MODEL, verbose_name='Approval By'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesOrders_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesOrders_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesOrders_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesOrders_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='customer',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Customers', verbose_name='Customers'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='ledger',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='Ledger'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='paymentdirection',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'PaymentDirection'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesOrders_PayDirection', to='sy.LookUp', verbose_name='Payment Direction'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.PaymentsMethods', verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='transtype',
            field=models.ForeignKey(limit_choices_to={'isreceipt': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.TransTypes', verbose_name='Trans Type'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='treasury',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Treasuries', verbose_name='treasury'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='treasurycenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TLTreasuriesOrders_cc1', to='gl.CostCenters', verbose_name='Treasury Cost center 1'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='treasurycenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TLTreasuriesOrders_cc2', to='gl.CostCenters', verbose_name='Treasury Cost center 2'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='treasurycenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TLTreasuriesOrders_cc3', to='gl.CostCenters', verbose_name='Treasury Cost center 3'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='treasurycenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TLTreasuriesOrders_cc4', to='gl.CostCenters', verbose_name='Treasury Cost center 4'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='treasuryledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesLedger', to='gl.Ledger', verbose_name='Treasury Ledger'),
        ),
        migrations.AddField(
            model_name='treasuriesorders',
            name='vendor',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.Vendors', verbose_name='Vendors'),
        ),
        migrations.AlterField(
            model_name='ledgerjour',
            name='islocked',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is Locked'),
        ),
        migrations.AlterField(
            model_name='taxestrans',
            name='closed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Closed'),
        ),
        migrations.AlterField(
            model_name='taxestrans',
            name='taxamount',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='taxestrans',
            name='taxbaseamount',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Tax Base Amount'),
        ),
        migrations.AlterField(
            model_name='taxestrans',
            name='taxpercent',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Tax Percent'),
        ),
        migrations.AlterField(
            model_name='transtypes',
            name='iscash',
            field=models.BooleanField(default=False, verbose_name='Is Cash'),
        ),
        migrations.AlterField(
            model_name='transtypes',
            name='ischeck',
            field=models.BooleanField(default=False, verbose_name='Is Check'),
        ),
        migrations.AlterField(
            model_name='transtypes',
            name='iscreditcard',
            field=models.BooleanField(default=False, verbose_name='Is Credit Card'),
        ),
        migrations.AlterField(
            model_name='treasuriesorders',
            name='isfinish',
            field=models.BooleanField(blank=True, default=False, verbose_name='Is finish'),
        ),
    ]
