# Generated by Django 2.2.3 on 2022-03-26 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl', '0003_remove_ledgerjour_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transtypes',
            name='transkind',
            field=models.ForeignKey(limit_choices_to={'keyname': '"TransKind"'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransTypes_TransKind', to='sy.LookUp', verbose_name='Trans Kind'),
        ),
        migrations.AlterField(
            model_name='treasuriesorders',
            name='accounttype',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': '"AccountType"'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesOrders_AccountType', to='sy.LookUp', verbose_name='Account Type'),
        ),
    ]
