# Generated by Django 2.2 on 2022-01-20 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gl', '0003_remove_ledgerjour_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treasuriesorders',
            name='approvalby',
        ),
    ]
