# Generated by Django 2.2.3 on 2022-03-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl', '0004_auto_20220326_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasuriesorders',
            name='accounttype',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('keyid', 90001), ('keyid', 90002), ('keyid', 90003), _connector='OR'), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TreasuriesOrders_AccountType', to='sy.LookUp', verbose_name='Account Type'),
        ),
    ]
