# Generated by Django 2.2.3 on 2022-03-28 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gl', '0005_auto_20220328_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transtypes',
            name='transkind',
            field=models.ForeignKey(limit_choices_to={'keyname': 'TransKind'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='TransTypes_TransKind', to='sy.LookUp', verbose_name='Trans Kind'),
        ),
    ]
