# Generated by Django 2.2.3 on 2022-05-18 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gl', '0006_auto_20220328_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerjour',
            name='created_by_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LedgerJour_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By '),
        ),
    ]
