# Generated by Django 2.0.9 on 2021-07-10 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, null=True, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('shortengname', models.CharField(max_length=100, null=True, verbose_name='Short Eng Name')),
                ('shortarbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Short Arb Name')),
                ('accountnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Account Number')),
                ('iban', models.CharField(blank=True, max_length=100, null=True, verbose_name='IBAN Number')),
                ('reconciliationenabled', models.BooleanField(default=False, verbose_name='Reconciliation Enabled')),
                ('prefixchequeno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Prefix Cheque Number')),
                ('suffixchequeno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Suffix Cheque Number')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='BanksAddresses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 1')),
                ('address2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address 2')),
                ('address3', models.CharField(blank=True, max_length=100, null=True, verbose_name='address 3')),
                ('street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('latitudes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitudes')),
                ('longitudes', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitudes')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('addresstype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.AddressesTypes', verbose_name='Address Type')),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bnk.Banks', verbose_name='Bank')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Cities', verbose_name='City')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Countries', verbose_name='Country')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.Districts', verbose_name='District')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='BanksCheques',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chequebooknum', models.CharField(blank=True, max_length=20, null=True, verbose_name='Cheque Book Num')),
                ('chequenum', models.CharField(blank=True, max_length=300, null=True, verbose_name='Cheque Num')),
                ('chequeserial', models.PositiveIntegerField(blank=True, null=True, verbose_name='Cheque Serial')),
                ('statusdate', models.DateField(blank=True, null=True, verbose_name='Status Date')),
                ('statusreason', models.CharField(blank=True, max_length=100, null=True, verbose_name='Status Reason')),
                ('beneficiaryname', models.CharField(blank=True, max_length=300, null=True, verbose_name='Beneficiary Name')),
                ('beneficiarycompanyname', models.CharField(blank=True, max_length=300, null=True, verbose_name='Beneficiary Company Name')),
                ('amount', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Amount')),
                ('amountfc', models.DecimalField(blank=True, decimal_places=12, max_digits=30, null=True, verbose_name='Amount Foreign Currency')),
                ('chequedate', models.DateField(blank=True, null=True, verbose_name='Cheque Date')),
                ('chequeduedate', models.DateField(blank=True, null=True, verbose_name='Cheque Due Date')),
                ('refpaymentid', models.IntegerField(blank=True, null=True, verbose_name='Reference Payment ID')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='Created Date')),
                ('accounttype', models.ForeignKey(blank=True, limit_choices_to={'keyname': 'AccountType'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BanksCheques_AccountType', to='sy.LookUp', verbose_name='Account Type')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bnk.Banks', verbose_name='Bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BanksCheques_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currenct')),
                ('customer', models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Customers', verbose_name='Customer')),
                ('ledger', models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='gl.Ledger', verbose_name='Ledger')),
                ('status', models.ForeignKey(blank=True, limit_choices_to={'keyname': 'ChequeStatus'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BanksCheques_Status', to='sy.LookUp', verbose_name='Cheque Status')),
                ('statuschangedby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Status Changed By')),
                ('vendor', models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='ap.Vendors', verbose_name='Vendor')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='BanksContacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
                ('value', models.CharField(max_length=300, verbose_name='Value')),
                ('inactive', models.BooleanField(verbose_name='Inactive')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bnk.Banks', verbose_name='Bank')),
                ('contacttype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.ContactsTypes', verbose_name='Contact Type')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='BanksCreditCardsTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commissionpercent', models.DecimalField(blank=True, decimal_places=4, max_digits=22, null=True, verbose_name='Commission Percent')),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bnk.Banks', verbose_name='Bank')),
                ('contacttype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sy.CreditCardsTypes', verbose_name='Credit Cards Type')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='BanksGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Code')),
                ('engname', models.CharField(max_length=100, null=True, verbose_name='Eng Name')),
                ('arbname', models.CharField(blank=True, max_length=100, null=True, verbose_name='Arb Name')),
            ],
            options={
                'ordering': ['code'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.AddField(
            model_name='banks',
            name='bankgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bnk.BanksGroups', verbose_name='Bank Group'),
        ),
        migrations.AddField(
            model_name='banks',
            name='bankledger',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': 'True'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Banks_bankledger', to='gl.Ledger', verbose_name='Bank Account Ledger'),
        ),
        migrations.AddField(
            model_name='banks',
            name='commissioncostcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Banks_Commissioncc1', to='gl.CostCenters', verbose_name='Commission Cost center 1'),
        ),
        migrations.AddField(
            model_name='banks',
            name='commissioncostcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Banks_Commissioncc2', to='gl.CostCenters', verbose_name='Commission Cost center 2'),
        ),
        migrations.AddField(
            model_name='banks',
            name='commissioncostcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Banks_Commissioncc3', to='gl.CostCenters', verbose_name='Commission Cost center 3'),
        ),
        migrations.AddField(
            model_name='banks',
            name='commissioncostcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Banks_Commissioncc4', to='gl.CostCenters', verbose_name='Commission Cost center 4'),
        ),
        migrations.AddField(
            model_name='banks',
            name='commissionledger',
            field=models.ForeignKey(blank=True, limit_choices_to={'allowaccountentry': 'True'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Banks_commissionledger', to='gl.Ledger', verbose_name='Bank Commission Ledger'),
        ),
        migrations.AddField(
            model_name='banks',
            name='costcenter1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Banks_cc1', to='gl.CostCenters', verbose_name='Cost center 1'),
        ),
        migrations.AddField(
            model_name='banks',
            name='costcenter2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Banks_cc2', to='gl.CostCenters', verbose_name='Cost center 2'),
        ),
        migrations.AddField(
            model_name='banks',
            name='costcenter3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Banks_cc3', to='gl.CostCenters', verbose_name='Cost center 3'),
        ),
        migrations.AddField(
            model_name='banks',
            name='costcenter4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Banks_cc4', to='gl.CostCenters', verbose_name='Cost center 4'),
        ),
        migrations.AddField(
            model_name='banks',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.Currency', verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='banks',
            name='status',
            field=models.ForeignKey(blank=True, limit_choices_to={'keyname': 'BankStatus'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Bank_Status', to='sy.LookUp', verbose_name='Bank Status'),
        ),
    ]
