# Generated by Django 2.2 on 2021-09-29 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bnk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankscreditcardstypes',
            old_name='contacttype',
            new_name='creditcardtype',
        ),
        migrations.CreateModel(
            name='BanksDocumentsUnderProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourcename', models.CharField(blank=True, max_length=300, null=True, verbose_name='Source Table Name')),
                ('sourceid', models.PositiveIntegerField(blank=True, null=True, verbose_name='Source ID')),
                ('bankrefno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Reference Number')),
                ('bankrefdate', models.DateField(blank=True, null=True, verbose_name='Bank Reference Date')),
                ('isclose', models.BooleanField(default=False, verbose_name='Is Close')),
                ('created_date', models.DateField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('updated_date', models.DateField(auto_now_add=True, null=True, verbose_name='Updated Date')),
                ('remarks', models.CharField(blank=True, max_length=100, null=True, verbose_name='Remarks')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BanksDocumentsUnderProcess_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('paymentdirection', models.ForeignKey(blank=True, limit_choices_to={'keyname': 'PaymentDirection'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BanksDocumentsUnderProcess_PaymentDirection', to='sy.LookUp', verbose_name='Payment Status')),
                ('paymentmethod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BanksDocumentsUnderProcess_Paymethod', to='sy.PaymentsMethods', verbose_name='Payment Method')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='BanksDocumentsUnderProcess_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Updated_by By')),
            ],
            options={
                'ordering': ['pk'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
