# Generated by Django 2.2 on 2021-09-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ar', '0002_auto_20210929_1512'),
        ('inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='targetbuildingblocks',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['pk']},
        ),
        migrations.RenameField(
            model_name='inventorieslocations',
            old_name='counrty',
            new_name='country',
        ),
        migrations.RemoveField(
            model_name='targetbuildingblockschannelsitems',
            name='monthly_target',
        ),
        migrations.AddField(
            model_name='items',
            name='safetystock',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Safety Stock Month'),
        ),
        migrations.AddField(
            model_name='items',
            name='shelflife',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Shelf Life Month'),
        ),
        migrations.AddField(
            model_name='operationstypes',
            name='allowcashdiscount',
            field=models.BooleanField(default=False, verbose_name='Allow Cash Discount'),
        ),
        migrations.AddField(
            model_name='targetbuildingblockschannelsitems',
            name='large',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Large'),
        ),
        migrations.AddField(
            model_name='targetbuildingblockschannelsitems',
            name='medium',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Medium'),
        ),
        migrations.AddField(
            model_name='targetbuildingblockschannelsitems',
            name='small',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Small'),
        ),
        migrations.AlterField(
            model_name='inventoriesbinlocations',
            name='barcode',
            field=models.CharField(max_length=100, unique=True, verbose_name='Barode'),
        ),
        migrations.AlterField(
            model_name='inventoriesbinlocations',
            name='bin',
            field=models.CharField(max_length=100, null=True, verbose_name='Bin'),
        ),
        migrations.AlterField(
            model_name='inventoriesbinlocations',
            name='floor',
            field=models.CharField(max_length=50, verbose_name='Floor'),
        ),
        migrations.AlterField(
            model_name='inventoriesbinlocations',
            name='shelf',
            field=models.CharField(max_length=100, null=True, verbose_name='Shelf'),
        ),
        migrations.AlterField(
            model_name='inventoriesbinlocations',
            name='track',
            field=models.CharField(max_length=100, null=True, verbose_name='Track'),
        ),
        migrations.AlterField(
            model_name='inventoriesbinlocations',
            name='zone',
            field=models.CharField(max_length=100, null=True, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='inventorieslocations',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.Warehouses', verbose_name='Warehouse Related Cost Price'),
        ),
        migrations.AlterField(
            model_name='items',
            name='allowecommerce',
            field=models.BooleanField(default=False, verbose_name='Allow E Commerce'),
        ),
        migrations.AlterField(
            model_name='items',
            name='aso',
            field=models.BooleanField(default=False, verbose_name='Administrative Services Only'),
        ),
        migrations.AlterField(
            model_name='items',
            name='controlled',
            field=models.BooleanField(default=False, verbose_name='Controlled'),
        ),
        migrations.AlterField(
            model_name='items',
            name='highalter',
            field=models.BooleanField(default=False, verbose_name='High Alter'),
        ),
        migrations.AlterField(
            model_name='items',
            name='lasa',
            field=models.BooleanField(default=False, verbose_name='Look-Alike/Sound-Alike'),
        ),
        migrations.AlterField(
            model_name='items',
            name='multidosage',
            field=models.BooleanField(default=False, verbose_name='Multi Dosage'),
        ),
        migrations.AlterField(
            model_name='items',
            name='prescribed',
            field=models.BooleanField(default=False, verbose_name='Prescribed'),
        ),
        migrations.AlterField(
            model_name='items',
            name='taxgroupPurchaseincludedprice',
            field=models.BooleanField(default=False, verbose_name='Tax Included Purchase Price'),
        ),
        migrations.AlterField(
            model_name='items',
            name='taxgroupsaleincludedprice',
            field=models.BooleanField(default=False, verbose_name='Tax Included sale Price'),
        ),
        migrations.AlterField(
            model_name='itemsclasses',
            name='autobarcode',
            field=models.BooleanField(default=False, verbose_name='Auto Barcode'),
        ),
        migrations.AlterField(
            model_name='itemscosts',
            name='transdate',
            field=models.DateField(null=True, verbose_name='Transaction Date'),
        ),
        migrations.AlterField(
            model_name='itemscosts',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.Warehouses', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='itemspriceslists',
            name='invlocation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.InventoriesLocations', verbose_name='Inventory Location'),
        ),
        migrations.AlterField(
            model_name='itemspriceslists',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.Units', verbose_name='Unit'),
        ),
        migrations.AlterField(
            model_name='operations',
            name='salesperson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ar.Salesmans', verbose_name='Salesman'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='allowadditem',
            field=models.BooleanField(default=False, verbose_name='Allow Add New Item'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='allowadjustqty',
            field=models.BooleanField(default=False, verbose_name='Allow Adjust Original Qty'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='allowdeleteitem',
            field=models.BooleanField(default=False, verbose_name='Allow Delete Item'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='allowrevise',
            field=models.BooleanField(default=False, verbose_name='Allow Revise'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='defaultdiscounttype',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='Default Discount Type'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='effectcostprice',
            field=models.BooleanField(default=False, verbose_name='Iseffecting Item Cost Price'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='isinventory',
            field=models.BooleanField(default=False, verbose_name='Is Inventory Transaction'),
        ),
        migrations.RemoveField(
            model_name='operationstypes',
            name='possibleparent',
        ),
        migrations.AddField(
            model_name='operationstypes',
            name='possibleparent',
            field=models.ManyToManyField(related_name='_operationstypes_possibleparent_+', to='inv.OperationsTypes', verbose_name='Parent Possible'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='usecostcenter1',
            field=models.BooleanField(default=False, verbose_name='Use Cost Center 1'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='usecostcenter2',
            field=models.BooleanField(default=False, verbose_name='Use Cost Center 2'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='usecostcenter3',
            field=models.BooleanField(default=False, verbose_name='Use Cost Center 3'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='usecostcenter4',
            field=models.BooleanField(default=False, verbose_name='Use Cost Center 4'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='usedepartment',
            field=models.BooleanField(default=False, verbose_name='Use Department'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='usedisc1',
            field=models.BooleanField(default=False, verbose_name='Use Discount 1'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='usedisc2',
            field=models.BooleanField(default=False, verbose_name='Use Discount 2'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='usedisc3',
            field=models.BooleanField(default=False, verbose_name='Use Discount 3'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='useexpense',
            field=models.BooleanField(default=False, verbose_name='Use Expense'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='usepaymethod',
            field=models.BooleanField(default=False, verbose_name='Use Pay Methods'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='useref1',
            field=models.BooleanField(default=False, verbose_name='Reference 1'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='useref2',
            field=models.BooleanField(default=False, verbose_name='Reference 2'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='useref3',
            field=models.BooleanField(default=False, verbose_name='Reference 3'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='usesaleperson',
            field=models.BooleanField(default=False, verbose_name='Use Sales Person'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='useshipping',
            field=models.BooleanField(default=False, verbose_name='Use Shipping'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='viewaccountbalance',
            field=models.BooleanField(default=False, verbose_name='View Account Balance'),
        ),
        migrations.AlterField(
            model_name='operationstypes',
            name='viewlocationqty',
            field=models.BooleanField(default=False, verbose_name='View Qty In All Locations'),
        ),
        migrations.AlterField(
            model_name='targetbuildingblockschannelsitems',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.Items', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='targetbuildingblockschannelsitems',
            name='itemuom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.ItemsUOM', verbose_name='Unit Of Measurement'),
        ),
        migrations.AlterUniqueTogether(
            name='targetbuildingblockschannels',
            unique_together={('channel', 'year')},
        ),
    ]
