# Generated by Django 2.2 on 2022-01-24 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inv', '0002_auto_20210929_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericnames',
            name='genericcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inv.GenericNamesCategories', verbose_name='Generic Category'),
        ),
    ]
